### ISSUE TITLE
Tutorial: AssertionError: Your sequence must be DNA!

### ISSUE THREAD

**Issue by ljcohen** [dib-lab/kevlar#164]
From the [tutorial](http://kevlar.readthedocs.io/en/stable/quick-start.html) with this command:

```
kevlar simplex \
    --case proband.fq.gz --case-min 6 \
    --control mother.fq.gz --control father.fq.gz --ctrl-max 0 \
    --novel-memory 5M --novel-fpr 0.6 --threads 4 \
    --filter-memory 1M --filter-fpr 0.005 \
    --mask-files refr.fq.gz --mask-memory 5M \
    --ksize 25 --out variant-calls.vcf refr.fq.gz
```

The following error was raised:

```
[kevlar::filter] Loading mask from ['refr.fq.gz']
    1 sequences and 2499976 k-mers consumed; estimated false positive rate is 0.002
[kevlar::filter] Mask loaded in 1.04 sec
[kevlar::partition] Loading reads
[kevlar::filter] Loading input; recalculate k-mer abundances, de-duplicate reads and merge k-mers
Traceback (most recent call last):
  File "/mnt/home/ljcohen/.conda/envs/dammit/bin/kevlar", line 11, in <module>
    sys.exit(main())
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/__main__.py", line 33, in main
    mainmethod(args)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/simplex.py", line 107, in main
    for variant in workflow:
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/simplex.py", line 70, in simplex
    for cc in partitioner:
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/partition.py", line 25, in partition
    graph.load(readstream, minabund=minabund, maxabund=maxabund)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/readgraph.py", line 62, in load
    for record in readstream:
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/filter.py", line 106, in filter
    for record in readstream:
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/novel.py", line 137, in novel
    minkmer = kevlar.revcommin(kmer)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/__init__.py", line 81, in revcommin
    rc = revcom(seq)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/kevlar/__init__.py", line 77, in revcom
    return screed.dna.reverse_complement(str(seq))
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/screed/dna.py", line 27, in reverse_complement
    assert is_DNA(s), "Your sequence must be DNA!"
AssertionError: Your sequence must be DNA!
```

Are there illegal letters in the file?

**Comment by standage** [comment]
Weird. There shouldn't be any non-ACGT characters in the sequence data.

Just a thought: What version of screed and khmer do you have installed?

**Comment by ljcohen** [comment]
```
(kevlar-env) [ljcohen@dev-intel14 fastq2]$ interleave-reads.py --version

|| This is the script interleave-reads.py in khmer.
|| You are running khmer version 3.0.0a1+20.gc0700ce
|| You are also using screed version 1.0
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

khmer 3.0.0a1+20.gc0700ce```
